type Query {
    getObjectS3(key:String):String
}
type Mutation {
    uploadS3(key:String,body:String):String,
    sendSMS(phoneNumber:String,message:String):String,
    sendEmail(key:String,body:String):String,
}
schema {
  query: Query
  mutation: Mutation
}